nodejs/diagnostics

docs/AsyncWrap/README.md
docs/README.md
docs/perf-events/README.md
docs/platform-tracing/README.md
docs/v8-tracing/README.md

for issue #22 "add docs directory to repo"

initial stab at some tracing docs

---

README.md

I've been working with errors and instrumentation in Node for a couple of years. I'd like to join the working group to be more involved with the development and improvement of the tracing api's etc within Node. I'm an experienced Node dev and have been working full time with Node since around v0.4/0.8
NPM: https://www.npmjs.com/~watson
Thanks :)

Request to join Tracing WG

---

docs/AsyncWrap/README.md
docs/AsyncWrap/example-run.js
docs/AsyncWrap/example-trace.js

This should be an up to date documentation on the AsyncWrap API. I have not included in discussion on the future of the API, but there a small section (Things you might not expect) on some stuff that other users should know.
Also I'm not really sure what the purpose of the provider argument is and how it compares to `this.constructor.name` someone else should elaborate on that. 
PS: I've heard my spelling isn't ideal, bear with me.

docs: add up to date documentation for AsyncWrap

---

wg-meetings/2015-11-19.md

could someone review and merge?

added 2015-11-19 meeting minutes

---

docs/AsyncWrap/README.md
docs/AsyncWrap/example-trace/run.js
docs/AsyncWrap/example-trace/trace.js

This documents the changes made in https://github.com/nodejs/node/pull/3461
/cc @trevnorris

Async wrap update - destroy hook and uid

---

docs/AsyncWrap/README.md
docs/AsyncWrap/example-trace/trace.js

nodejs/node#4600 added `uid` to all hooks among other `uid` related things.

docs: update after nodejs/node#4600

---

docs/AsyncWrap/README.md
docs/AsyncWrap/example-trace/trace.js

nodejs/node#5756 changed `setupHooks` to take an object as input and added `didThrow` as an argument to the `post` hook.

docs: update after nodejs/node#5756

---

wg-meetings/2016-06-01.md

Please check for technical and editorial accuracy. Thanks!
Closes #49.
/cc @mhdawson @matthewloring @ofrobots @paulirish @pavelfeldman @caseq @jasonlaster @pmuellr @fmeawad @auchenberg

Meetings: Add notes from 2016-06-01 meeting.

---

wg-meetings/2016-07-13.md

Add July meeting notes

---

GOVERNANCE.md
LICENSE.md

Fixes #69 (together with https://github.com/nodejs/node/pull/9329).
GOVERNANCE is mostly copied boilerplate from https://github.com/nodejs/node/blob/master/WORKING_GROUPS.md#bootstrap-governance
LICENSE is MIT per current Foundation policy.
@nodejs/tsc can you take a look? Thanks!

meta: add governance and license docs

---

wg-meetings/2016-12-02.md

Captures major discussion points and next steps from Diagnostics group meeting after Node Interactive.
@nodejs/diagnostics it was great working together at the summit on Friday. quite an intense discussion which hopefully deepened our shared understandings and goals. we also reached some decisions and concrete next steps in several areas 🎉 . PTAL if the discussion points and next steps captured in these notes are correct.
We could really 🙏  use your help in implementing and/or opening issues accordingly 😄 
Also could you please add to this thread those who were in the meeting but not on the Diagnostics alias? Thanks!

2016-12-02 - Node Interactive - Notes

---

wg-meetings/2016-11-09.md

docs: add Diag WG 2016-11-09 minutes

---

README.md

I trace my diagnostics experience back to 2013 when I leaked gigabytes of RAM in the browser and stumbled upon some memory leaks in V8. I did fix the leaks and I've been helping my colleagues debug their JavaScript ever since.
My first version of node was 0.8, at the time of the 0.10 release, so I switched to 0.10 a few days in. My day job is focused on building maintainable software with a team where I'm the only person with extensive Node.js experience.
I enjoy teaching and I'm organizing community meet-ups in my area. My focus in teaching is the gap where people are not beginners anymore, but not ready to discover everything for themselves. With topics like debugging memory leaks.  
Things I hope to contribute to the WG:
- Make diagnostics accessible to less experienced developers.
- …

Request to join Diagnostics WG

---

README.md

Nominating @jkrems to the Diagnostics WG. Jan is the original author of [node-inspect](https://github.com/nodejs/node-inspect) and as a member could better contribute to that project.
@jkrems this does depend on you wanting to be a member of the WG. The main requirement is that you check and contribute to issues here occasionally and try to attend meetings. Your work on node-inspect is already more than enough IMO.
We should discuss at the next meeting according to protocol. To be sure we have consensus, anyone from @nodejs/diagnostics who has objections should please chime in here. Thank you!

wg: nominating jkrems

---

tracing/AsyncWrap/README.md

`fs.syncWrite` => `fs.writeSync`

doc: fix typo

---

tracing/AsyncHooks/problematic-modules.md

Just starting off the list some some well known sinners 😄 
Not sure if the phrase "async continuity" makes sense to people, but it was the best I could come up with - feel free to suggest something else

Add list of modules breaking async continuity

---

wg-meetings/2018-01-10.md

My notes were more sparse than usual, and I had technical difficulities during part of the call.  Please LMK if missed anything or got anything wrong.

adding minutes from 2018-10-01 meeting

---

debugging/README.md

As explained by https://github.com/nodejs/diagnostics/issues/189, the current doc is not up to date with the latest development around new debugger API, specially the v8-inspector protocol.
If you have any clarification, i will happily modify my PR !

debugging: rewrite to be more up-to-date

---

README.md

This PR adds the champions table to the README as mentioned in #185.
I'm not aware of who is championing some of the issues, so for now they are listed under "need volunteers". Please let me know if there are any additions I should make (also, the branch is editable by maintainers).

add champion/stakeholders table

---

README.md

@rmg removed themselves from the @nodejs/diagnostics team on June 20. Resynch the list of people in the README against the GitHub team.
(The team currently has 31 people. If there are really that many people active in the Diagnostics WG, then awesome! But if that contains a lot of folks who aren't active anymore, it might be a good idea to do some pruning. Or not if extra folks don't adversely affect anything. In some groups, that can be a problem when doing things like taking votes or abiding by rules about quorum.)

resync team with README

---

README.md

Remove `Node report in core` from Current list of
initiatives, as this is achieved. Report has landed.
Refs: https://github.com/nodejs/node/pull/22712
cc @mhdawson

doc: Remove `Node report in core` initiative

---

summits/2019-03/README.md

Add notes from Munich summit

---

README.md

@Flarna and @Hollerberg are driving this topic for my organization for a while now and my responsibilities have changed. Hence, I'd request to be moved to emeritus status.

Move Daniel Khan to Emeritus

---

documentation/abnormal_termination/step1/using_exit_stack_traces.md

Confirming if the process was exited for proactive invocation of `process.exit`.
The option is available after https://github.com/nodejs/node/pull/30516 has been landed.

doc: add abnormal termination step 1

---

README.md

At the Collaborator Summit following Node+JS Interactive 2019 in Montreal, I took over the champion responsibility for async_hooks.
@ofrobots This PR is replacing you as champion in the doc. Would you like to retain champion status or are you fine with me removing your name here?

doc: change champion of async_hooks to @Qard

---

documentation/abnormal_termination/README.md
documentation/abnormal_termination/step2/using_diagnostic_report.md
documentation/abnormal_termination/step3/using_lldb.md
documentation/abnormal_termination/step4/using_valgrind.md

I incorporated the docs from the first deep dive (process crash) to our guides:
https://docs.google.com/document/d/1gd_4hlDK-DacbyTnFcqLPdCjM1Q1z02MdkFaUddPLCE/edit?ts=5de804b8#

docs(documentation): improve process crash

---

documentation/hang/step1/using_trace_sigint.md

Step 1 of diagnosing hanging Node.js processes.

doc: add --trace-sigint diagnosing document

---

wg-meetings/2020-02-12.md

Closes: https://github.com/nodejs/diagnostics/issues/354

doc: add minutes for meeting 2020-02-12

---

.github/workflows/stale.yml

Add Stale actions to help keep the issue tracker cleaner. Issues
inactive for 90 days will be marked as `stale`, and issues marked as
stale for 14 days will be automatically closed. The label `never stale`
can be used to skip certain issues.

chore(github): add stale action

---

wg-meetings/2020-10-28.md

Fixes: https://github.com/nodejs/diagnostics/issues/438

doc: add meeting minutes for 28th October

---

README.md

Glen Keane seems to have renamed their Github username from 'thekemkid' to 'GlenTiki'.
Github seems to be redirecting (301) the user's repo links but not the profile link.

Emeritus Member username updated

---

.github/workflows/stale.yml

Version 2 of actions/stale changed the option for
exempt issue labels from the singular 
`exempt-issue-label` 
to the plural 
`exempt-issue-labels`.
Refs: https://github.com/actions/stale/pull/19
Refs: https://github.com/nodejs/build/pull/2704

chore: fix exempt issue labels for stale bot
