- wg-meetings/2015-02-19.md
ported google doc. added attendees i remember.
> add feb 19th meeting.

- README.md
I just joined Ali (@ofrobots) at Google and will be working
on Google's trace agent for Node.js. I am hoping to join this
Working Group to stay up to date on tracing efforts happening
in the community and contribute to the discussion.
> Request to join Tracing Working Group

- README.md
I'd like to join this group.  I am the engineering manager of the New Relic Node Agent, and have a keen interest in helping improve node tracing.
> jeffo request to join

- wg-meetings/2016-01-26.md
Can some folks review? Pleae note stuff to add/remove/change or LGTM.
> minutes for 2016-01-26 meeting

- README.md
Just made this from the GitHub UI lol, hopefully there is still a newline at end of file...
see https://github.com/nodejs/diagnostics/issues/72
> add Fishrock123 as a WG member

- wg-meetings/2017-01-19.md
> docs: add WG meeting 2017-01-19

- README.md
It's been great working with you all and I look forward to continuing to contribute to Node Diagnostics as I can; due to changes though I'm retiring from official responsibilities. @mike-kaufman has volunteered to lead coordination now. Thanks!
> retire josh

- README.md
I will be moving on to a new position and will have less time
going forward to work on Node.js diagnostics.
> Removing matthewloring from diagnostics wg

- wg-meetings/2017-11-15.md
Please let me know if anything is missing/incorrect.
> adding minutes from 2017-11-15 wg meeting

- wg-meetings/2017-11-29.md
From my notes.  Please lmk if anything is incorrect/innacurate.  I had to drop off early & missed final discussion, so someone should fill in any relevant details there.
> adding minutes from 11-29 meeting

- wg-meetings/2017-05-11.md
> doc: add meeting minutes 2017-05-11

- wg-meetings/2017-12-13.md
Please let me know if anything is missing/incorrect.
> adding minutes from 12/13 meeting

- wg-meetings/2018-03-07.md
These are the notes I had taken + notes from the google doc.  Please let me know if anything is missing.
> adding minutes for 2018-03-07 meeting

- README.md
I would like to join the diagnostics team. For nearForm I am working on diagnostic tools and I use different tools a lot in general. Being more involved would be good in that case.
> Add BridgeAR to working group

- README.md
Update membership as per
https://github.com/nodejs/diagnostics/issues/217.
> doc: update members after membership review

- README.md
@jasnell as champion
@ofrobots as stakeholder
> Add jasnell as champion for Trace Events

- README.md
Provide a little bit of text about how to particiapte in the bi-weekly
meetings as well as the twice yearly face to face gathering.
Fixes: https://github.com/nodejs/diagnostics/issues/242
> doc: update README with info about meeting times

- README.md
Update to list Gireesh who is doing most of the work
and add the link to the PR.
> doc: update info about node-report

- README.md
so that I can contribute to the stated objective of this working group in ways I can, such as:
- working towards diagnostics tooling improvements
- diagnostic best practices content definition and development
- use insights from core to participate in defining consumability strategy
thanks in advance!
> readme: add gireeshpunathil to working group

- README.md
Adding my self as the CLS champion as agreed on today's meeting. Not sure if CLS is the official name though 🤔 
For now I've made a link to the current PR in Node core. I'll look into making an issue here in this repo as well.
(sorry for the bad diff, I couldn't help my self doing some cleanup of the table as well)
> Add @watson as CLS champion

- wg-meetings/2019-06-19.md
> WG Meeting notes 2019-06-19

- documentation/abnormal_termination/README.md
Reorganizing the Abnormal Termination landing page to be more focused on symptoms than tools. Instead of showing users the available tools, this new format will point users to the appropriate tool guide based on their symptoms.
> doc: symptom-diven Abnormal Termination intro

- documentation/memory/step4/using_native_tools.md
Signed-off-by: Michael Dawson <michael_dawson@ca.ibm.com>
> doc: add sec on investigating navite memory leaks

- README.md
I have not participated in meetings for a while, and my availability for OSS work is going to decrease by the end of the year for personal reasons (if you are curious, hit me up privately! It's a good thing!).
I've removed myself from the diagnostics team already on github.
> Moving Matteo to emeritus

- README.md
Add button to join the recently created #diagnostics-wg Slack channel on Node Slackers.
> doc: add button to join Slack channel

- wg-meetings/2020-09-30.md
Fixes: https://github.com/nodejs/diagnostics/issues/433
> doc: add minutes for meeting 30th september 2020

- wg-meetings/2022-06-28.md
Fixes: https://github.com/nodejs/diagnostics/issues/566
cc: @tony-go @gireeshpunathil
> doc: include 2022-06-28 meeting minutes

- wg-meetings/2022-07-26.md
> doc: add minutes 2022-07-26

- README.md
As per https://github.com/nodejs/diagnostics/issues/579#issuecomment-1218225393 from @mhdawson 
adding my profile to the membership list
> Add no9 membership

- wg-meetings/2022-08-23.md
> doc: add 2022-08-23 minutes

- wg-meetings/2022-09-20.md
> doc: add 20-09 meeting minutes

- README.md
Hi, I have not been active for a long time.
> Move AndreasMadsen to emeritus

- wg-meetings/2024-05-28.md
> doc: add May 28 notes

- wg-meetings/2024-06-27.md
> doc: add 2024-06-27 meeting notes
